# Generated by Django 4.2.7 on 2023-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('wage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branch',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tution', models.IntegerField(default=0)),
                ('Installment_number', models.PositiveSmallIntegerField(default=1)),
                ('percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('bank_email', models.EmailField(max_length=250)),
                ('bank_card_number', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('sms_fee', models.PositiveSmallIntegerField(default=250)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'Setting',
                'ordering': ('id',),
            },
        ),
    ]
