# Generated by Django 4.2.7 on 2023-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsetting',
            name='loan_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
