# Generated by Django 4.2.7 on 2023-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_installment_number_branchsetting_installment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsetting',
            name='percent',
        ),
        migrations.AddField(
            model_name='branchsetting',
            name='wage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
