# Generated by Django 4.2.7 on 2023-11-05 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('sex', models.CharField(choices=[('M', 'men'), ('W', 'women')], max_length=10)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('directorship', models.BooleanField(default=False)),
                ('is_inspector', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
