# Generated by Django 4.2.7 on 2023-11-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='clearing',
            new_name='termination',
        ),
    ]
