# Generated by Django 4.2.7 on 2023-11-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_rename_clearing_loan_termination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='wag_amount',
            new_name='wage_amount',
        ),
    ]
