# Generated by Django 4.2.7 on 2023-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_rename_wag_amount_loan_wage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_remaining',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='installment_paid',
            field=models.IntegerField(default=0),
        ),
    ]
