# Generated by Django 4.2.7 on 2023-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_installment_amount_loan_loan_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installment_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
