# Generated by Django 4.2.7 on 2023-11-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installment_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='wage_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
