# Generated by Django 4.2.7 on 2023-11-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0007_alter_transaction_options_and_more'),
        ('loan', '0008_alter_loan_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='bankaccount.transaction'),
        ),
    ]
