# Generated by Django 4.2.7 on 2023-11-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0005_alter_account_loan_status_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
